track_unknown_space: true
global_frame: map
rolling_window: false
robot_base_frame: base_link
footprint: [[0.1, 0.0], [0.0, 0.1], [-0.1, 0.0], [0.0, -0.1]] 

plugins:
- {name: static,            type: "costmap_2d::StaticLayer"}
- {name: explore_boundary,  type: "frontier_exploration::BoundedExploreLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
- {name: sensor,            type: "costmap_2d::ObstacleLayer"}
- {name: inflation,         type: "costmap_2d::InflationLayer"}

explore_boundary:
  resize_to_boundary: false #resize not needed as we are using gmapping
  frontier_travel_point: middle #next frontier pose using middle point of frontier
  #set to false for gmapping, true if re-exploring a known area
  explore_clear_space: false

sensor:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: /kobuki/laser/scan, inf_is_valid: true, raytrace_range: $(arg sensor_range), obstacle_range: $(arg sensor_range)}

inflation:
  inflation_radius: 0.15


ax_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot


robot_radius: 0.20  # distance a circular robot should be clearof the obstacle (kobuki: 0.18)

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.6
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             10
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space(no map)
  obstacle_range: 5.5
  raytrace_range: 6.0
  publish_voxel_map: false
  observation_sources:  scan
  scan: {data_type: LaserScan, topic: kobuki/laser/scan, marking: true, clearing: true, inf_is_valid: true}

#cost_scaling_factor and inflation_radius were now moved to theinflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true